name: Daily Naver Quiz Crawl

on:
  schedule:
    # GitHub Actions는 UTC로 돈다. 00:00 UTC = 한국 09:00
    - cron: "0 0 * * *"
  workflow_dispatch: {}  # 필요할 때 수동 실행 버튼

jobs:
  crawl:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          python -m playwright install --with-deps chromium

      - name: Run crawler
        run: |
          python crawler.py

      - name: Commit & push results
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add out/
          git commit -m "chore: update quizzes $(date -u +'%Y-%m-%d %H:%M:%S') UTC" || echo "no changes"
          git push
